services:
  db:
    image: postgres
    restart: always
    volumes:
      - psql-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evokare
      POSTGRES_USER: evokare
      POSTGRES_PASSWORD: evokar123

volumes:
  psql-data:
