version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - psql-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evokare
      POSTGRES_USER: evokare
      POSTGRES_PASSWORD: evokar123

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  psql-data:
